version: '2.4'
services:
  es01:
    container_name: es01
    build: ./configs
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JAVA_MEM} -Xmx${ES_JAVA_MEM}"
    mem_limit: ${ES_MEM}
    memswap_limit: 0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mainnet
  db:
    container_name: db
    image: mariadb:latest
    restart: on-failure
    ports:
      - 3306:3306
    mem_limit: ${DB_MEM}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:-root}
    volumes:
      - data-volume:/var/lib/mysql:cached # persist the db
      - ./configs:/etc/mysql/conf.d
      - ./data:/root/data # give access to dump files so we can load it when needed directly inside the container
    networks:
      - mainnet

  app:
    container_name: app
    restart: on-failure
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      ENV: ${ENV}
      SERVER_MODE: ${SERVER_MODE}
      ES_HOST: es01
      MYSQL_HOST: db
      MYSQL_PASS: ${MYSQL_PASS:-root}
    stdin_open: true
    tty: true
    volumes:
      - ./:/${APP_MOUNT:-/opt/app}:cached
    networks:
      - mainnet


volumes:
  esdata01:
    driver: local
  data-volume:
    driver: local

networks:
  mainnet:
